export enum AliasDeployedContracts {
  UtilsUpgradeable_Proxy = 'UtilsUpgradeable_Proxy',
  UtilsUpgradeable_Implementation = 'UtilsUpgradeable_Implementation',
  ProxyAdmin = 'ProxyAdmin',
  BribeUpgradeable_Implementation = 'BribeUpgradeable_Implementation',
  Pair_Implementation = 'Pair_Implementation',
  UniswapV2PartialRouter = 'UniswapV2PartialRouter',
  VoterUpgradeable_Implementation = 'VoterUpgradeable_Implementation',
  VoterUpgradeable_Proxy = 'VoterUpgradeable_Proxy',
  VotingEscrowUpgradeable_Proxy = 'VotingEscrowUpgradeable_Proxy',
  VotingEscrowUpgradeable_Implementation = 'VotingEscrowUpgradeable_Implementation',
  VeArtProxy = 'VeArtProxy',
  VeArtProxyStatic = 'VeArtProxyStatic',
  RouterV2 = 'RouterV2',
  PairAPIUpgradeable_Implementation = 'PairAPIUpgradeable_Implementation',
  PairAPIUpgradeable_Proxy = 'PairAPIUpgradeable_Proxy',
  RewardAPIUpgradeable_Implementation = 'RewardAPIUpgradeable_Implementation',
  RewardAPIUpgradeable_Proxy = 'RewardAPIUpgradeable_Proxy',
  CompoundVeNESTManagedNFTStrategyUpgradeable_Implementation = 'CompoundVeNESTManagedNFTStrategyUpgradeable_Implementation',
  PairFactoryUpgradeable_Implementation = 'PairFactoryUpgradeable_Implementation',
  PairFactoryUpgradeable_Proxy = 'PairFactoryUpgradeable_Proxy',
  FeesVaultFactoryUpgradeable_Implementation = 'FeesVaultFactoryUpgradeable_Implementation',
  FeesVaultFactoryUpgradeable_Proxy = 'FeesVaultFactoryUpgradeable_Proxy',
  RouterV2PathProviderUpgradeable_Implementation = 'RouterV2PathProviderUpgradeable_Implementation',
  RouterV2PathProviderUpgradeable_Proxy = 'RouterV2PathProviderUpgradeable_Proxy',
  CompoundVeNESTManagedNFTStrategyFactoryUpgradeable_Implementation = 'CompoundVeNESTManagedNFTStrategyFactoryUpgradeable_Implementation',
  CompoundVeNESTManagedNFTStrategyFactoryUpgradeable_Proxy = 'CompoundVeNESTManagedNFTStrategyFactoryUpgradeable_Proxy',
  ManagedNFTManagerUpgradeable_Implementation = 'ManagedNFTManagerUpgradeable_Implementation',
  ManagedNFTManagerUpgradeable_Proxy = 'ManagedNFTManagerUpgradeable_Proxy',
  MerklGaugeMiddleman = 'MerklGaugeMiddleman',
  BribeFactoryUpgradeable_Implementation = 'BribeFactoryUpgradeable_Implementation',
  BribeFactoryUpgradeable_Proxy = 'BribeFactoryUpgradeable_Proxy',
  VeNFTAPIUpgradeable_Implementation = 'VeNFTAPIUpgradeable_Implementation',
  VeNFTAPIUpgradeable_Proxy = 'VeNFTAPIUpgradeable_Proxy',
  PerpetualsTradersRewarderUpgradeable_Implementation = 'PerpetualsTradersRewarderUpgradeable_Implementation',
  PerpetualsTradersRewarderUpgradeable_Proxy = 'PerpetualsTradersRewarderUpgradeable_Proxy',
  VeBoostUpgradeable_Implementation = 'VeBoostUpgradeable_Implementation',
  VeBoostUpgradeable_Proxy = 'VeBoostUpgradeable_Proxy',
  MinterUpgradeable_Implementation = 'MinterUpgradeable_Implementation',
  MinterUpgradeable_Proxy = 'MinterUpgradeable_Proxy',
  VeNestSplitMerklAidropUpgradeable_Implementation = 'VeNestSplitMerklAidropUpgradeable_Implementation',
  VeNestSplitMerklAidropUpgradeable_Proxy = 'VeNestSplitMerklAidropUpgradeable_Proxy',
  RNest = 'RNest',
  NestRaiseUpgradeable_Implementation = 'NestRaiseUpgradeable_Implementation',
  NestRaiseUpgradeable_Proxy = 'NestRaiseUpgradeable_Proxy',
  FeesVaultUpgradeable_Implementation = 'FeesVaultUpgradeable_Implementation',
  PerpetualsGaugeUpgradeable_Implementation = 'PerpetualsGaugeUpgradeable_Implementation',
  PerpetualsGaugeUpgradeable_Proxy = 'PerpetualsGaugeUpgradeable_Proxy',
  VeNestDistributorUpgradeable_Implementation = 'VeNestDistributorUpgradeable_Implementation',
  VeNestDistributorUpgradeable_Proxy = 'VeNestDistributorUpgradeable_Proxy',
  SingelTokenVirtualRewarderUpgradeable_Implementation = 'SingelTokenVirtualRewarderUpgradeable_Implementation',
  GaugeFactoryUpgradeable_Implementation = 'GaugeFactoryUpgradeable_Implementation',
  GaugeFactory_V2Pools_Proxy = 'GaugeFactory_V2Pools_Proxy',
  GaugeFactory_V3Pools_Proxy = 'GaugeFactory_V3Pools_Proxy',
  GaugeUpgradeable_V2Pools_Implementation = 'GaugeUpgradeable_V2Pools_Implementation',
  GaugeUpgradeable_V3Pools_Implementation = 'GaugeUpgradeable_V3Pools_Implementation',
  AlgebraNESTPriceProviderUpgradeable_Implementation = 'AlgebraNESTPriceProviderUpgradeable_Implementation',
  AlgebraNESTPriceProviderUpgradeable_Proxy = 'AlgebraNESTPriceProviderUpgradeable_Proxy',
  Nest = 'Nest',
  MinimalLinearVestingUpgradeable_Proxy = 'MinimalLinearVestingUpgradeable_Proxy',
  MinimalLinearVestingUpgradeable_Implementation = 'MinimalLinearVestingUpgradeable_Implementation',
  GaugeRewader_Implementation = 'GaugeRewader_Implementation',
  GaugeRewader_Proxy = 'GaugeRewader_Proxy',
  AlgebraFactory_Proxy = 'AlgebraFactory_Proxy',
  BasePluginV1Factory_Proxy = 'BasePluginV1Factory_Proxy',
  ManualNESTPriceProvider = 'ManualNESTPriceProvider',
  OpenOceanVeNftDirectBuyer = 'OpenOceanVeNftDirectBuyer',
  GetInformationAggregatorUpgradeable_ProxyAdmin = 'GetInformationAggregatorUpgradeable_ProxyAdmin',
  GetInformationAggregatorUpgradeable_Proxy = 'GetInformationAggregatorUpgradeable_Proxy',
  GetInformationAggregatorUpgradeable_Implementation = 'GetInformationAggregatorUpgradeable_Implementation',
  BribeVeNESTRewardToken_Proxy = 'BribeVeNESTRewardToken_Proxy',
  BribeVeNESTRewardToken_Implementation = 'BribeVeNESTRewardToken_Implementation',
  CustomBribeRewardRouter_Proxy = 'CustomBribeRewardRouter_Proxy',
  CustomBribeRewardRouter_Implementation = 'CustomBribeRewardRouter_Implementation',
  CompoundEmissionExtensionUpgradeable_Proxy = 'CompoundEmissionExtensionUpgradeable_Proxy',
  CompoundEmissionExtensionUpgradeable_Implementation = 'CompoundEmissionExtensionUpgradeable_Implementation',
}

enum ContractsInstanceName {
  GetInformationAggregatorUpgradeable = 'GetInformationAggregatorUpgradeable',
  UtilsUpgradeable = 'UtilsUpgradeable',
  ProxyAdmin = 'ProxyAdmin',
  BribeUpgradeable = 'BribeUpgradeable',
  Pair = 'Pair',
  UniswapV2PartialRouter = 'UniswapV2PartialRouter',
  VoterUpgradeable = 'VoterUpgradeableV2',
  VotingEscrowUpgradeable = 'VotingEscrowUpgradeableV2',
  VeArtProxy = 'VeArtProxy',
  VeArtProxyStatic = 'VeArtProxyStatic',
  RouterV2 = 'RouterV2',
  PairAPIUpgradeable = 'PairAPIUpgradeable',
  RewardAPIUpgradeable = 'RewardAPIUpgradeable',
  CompoundVeNESTManagedNFTStrategyUpgradeable = 'CompoundVeNESTManagedNFTStrategyUpgradeable',
  GaugeUpgradeable = 'GaugeUpgradeable',
  PairFactoryUpgradeable = 'PairFactoryUpgradeable',
  FeesVaultFactoryUpgradeable = 'FeesVaultFactoryUpgradeable',
  RouterV2PathProviderUpgradeable = 'RouterV2PathProviderUpgradeable',
  CompoundVeNESTManagedNFTStrategyFactoryUpgradeable = 'CompoundVeNESTManagedNFTStrategyFactoryUpgradeable',
  ManagedNFTManagerUpgradeable = 'ManagedNFTManagerUpgradeable',
  MerklGaugeMiddleman = 'MerklGaugeMiddleman',
  BribeFactoryUpgradeable = 'BribeFactoryUpgradeable',
  VeNFTAPIUpgradeable = 'VeNFTAPIUpgradeable',
  PerpetualsTradersRewarderUpgradeable = 'PerpetualsTradersRewarderUpgradeable',
  VeBoostUpgradeable = 'VeBoostUpgradeable',
  MinterUpgradeable = 'MinterUpgradeable',
  VeNestSplitMerklAidropUpgradeable = 'VeNestSplitMerklAidropUpgradeable',
  RNest = 'RNest',
  NestRaiseUpgradeable = 'NestRaiseUpgradeable',
  FeesVaultUpgradeable = 'FeesVaultUpgradeable',
  PerpetualsGaugeUpgradeable = 'PerpetualsGaugeUpgradeable',
  VeNestDistributorUpgradeable = 'VeNestDistributorUpgradeable',
  SingelTokenVirtualRewarderUpgradeable = 'SingelTokenVirtualRewarderUpgradeable',
  GaugeFactoryUpgradeable = 'GaugeFactoryUpgradeable',
  AlgebraNESTPriceProviderUpgradeable = 'AlgebraNESTPriceProviderUpgradeable',
  Nest = 'Nest',
  TransparentUpgradeableProxy = 'TransparentUpgradeableProxy',
  MinimalLinearVestingUpgradeable = 'MinimalLinearVestingUpgradeable',
  GaugeRewarder = 'GaugeRewarder',
  ManualNESTPriceProvider = 'ManualNESTPriceProvider',
  OpenOceanVeNftDirectBuyer = 'OpenOceanVeNftDirectBuyer',
  BribeVeNESTRewardToken = 'BribeVeNESTRewardToken',
  CustomBribeRewardRouter = 'CustomBribeRewardRouter',
  CompoundEmissionExtensionUpgradeable = 'CompoundEmissionExtensionUpgradeable',
}

enum ContractsMocksInstanceName {
  ERC20OwnableMock = 'ERC20OwnableMock',
}

export const InstanceName = {
  ...ContractsInstanceName,
  ...ContractsMocksInstanceName,
};

export type InstanceName = ContractsInstanceName | ContractsMocksInstanceName;
